# This is a generated file. Not intended for manual editing.
services:
  webapplication1:
    build:
      context: "/Users/salvadiaz/RiderProjects/WebApplication1"
      dockerfile: "WebApplication1/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/WebApplication1.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "webapplication1:dev"
    ports: []
    volumes:
    - "/Users/salvadiaz/.nuget/packages:/home/app/.nuget/packages"
    - "/Users/salvadiaz/RiderProjects/WebApplication1/WebApplication1:/app:rw"
    - "/Users/salvadiaz/RiderProjects/WebApplication1:/src:rw"
    working_dir: "/app"
